// Generated by Wrangler on Fri Sep 13 2024 16:08:17 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	MAPBOX_FRONTEND_KEY: string;
	MAPBOX_BACKEND_KEY: string;
	OWM_KEY: string;
	AI: Ai;
}
