// Generated by Wrangler on Sat Jun 01 2024 13:59:47 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	MAPBOX_FRONTEND_KEY: string;
	MAPBOX_BACKEND_KEY: string;
	OWM_KEY: string;
}
